### PR TITLE
Fix build and lintian errors

### PR DESCRIPTION
**Pull request by basilgello**

### CODE REVIEW

**Comment by basilgello** [comment]
@phunkyfish

**Comment by phunkyfish** [comment]
Looks ok. Please bump version and add changelog

**Comment by phunkyfish** [comment]
You have a build error on windows but I don’t see that you have touched that code.

@AlwinEsch did all windows platforms used to build correctly for this addon?

**Comment by basilgello** [comment]
Yes, that's strange! I only touched the code triggered if no live555 is present, but makefile fails to unpack live555 if I interpret logs correctly.

**Comment by phunkyfish** [comment]
Maybe it’s a mirror issue. Maybe try pushing a change in the morning to see if it self heals.

**Comment by basilgello** [comment]
@phunkyfish something weird with tinyxml patch step:

```
No update step for 'tinyxml'
  Performing patch step for 'tinyxml'
CUSTOMBUILD : error : Target (for copy_if_different command) "" is not a directory. [D:\a\1\s\build\tinyxml.vcxproj]
```

**Pull request merged**
