### PR TITLE
Series timer support

### PR DESCRIPTION
**Pull request by margro**
this PR adds series timer support based on the new Jarvis PVR API functionality

### CODE REVIEW

**Comment by ksooo** [comment]
Please do not forget a PR for the Jarvis branch if you want this in Jarvis.

**Comment by ksooo** [comment]
... and no addon version bump for this changes. Really?

**Comment by ksooo** [comment]
... never mind. Just saw you pushed directly to Jarvis. All good.

**Comment by margro** [comment]
The version bump is actually there. It is the 1.12.0 bump. It was just that you created the Jarvis branch + master version bump before this PR was merged, so the PR was for master and conflicted with your version bump.

**Comment by ksooo** [comment]
> It was just that you created the Jarvis branch + master version bump before this PR was merged

 Yeah, all good - as I already wrote. ;-)

**Pull request merged**
