### PR TITLE
Coverity fixes

### PR DESCRIPTION
**Pull request by margro**
This PR fixes various coverity issues

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
@hudokkow @margro , RC1 is coming up. Is this something that should/can be included?

**Comment by Jalle19** [comment]
@MartijnKaijser most likely
@margro can you bump the version/changelog before we merge?

**Comment by hudokkow** [comment]
No objections from me. I've been doing fixes for other addons but my time this week and next is close to zero (parents visiting).
BTW, any way to extract a report from coverity? The report page drives me nuts. Every single action is sloooowww.

@margro, I started from the bottom, wmc, vuplus, etc. No need to duplicate work.

**Comment by MartijnKaijser** [comment]
@hudokkow no export that i know of. Sometimes it is slow but most of the time it's quite ok.

**Comment by margro** [comment]
@Jalle19: done
@MartijnKaijser: yes, the code changes are minimal and I tested here on Linux and Windows. Should be safe for RC1
@hudokkow: I've only update my addons so as far a I'm aware, we didn't do duplicate work.
Furthermore, I've assigned all Coverity issues that I solved to myself before solving them...

**Comment by MartijnKaijser** [comment]
since Isengard is already branch for all PVR add-ons, should this be included in that release it also needs to be merged in that branch

**Pull request merged**
