### PR TITLE
Update to PVR addon API v4.0.0

### PR DESCRIPTION
**Pull request by ksooo**
This PR implements all changes needed to properly support PVR Addon API v4.0.0, including a PVR addon micro version bump.

Details can be found here: https://github.com/xbmc/xbmc/pull/8005

### CODE REVIEW

**Comment by margro** [comment]
Why did you change the internal addon fields from int to unsigned int? The -1 values are for a reason since 0 is a valid id from the backend. This breaks the funtionality of the addon!
Please don't ever do this again in a "version bump"!

**Comment by ksooo** [comment]
Nice to hear something from someone who seems to feel responsible for this addon. Great!

Maybe you could start to follow the PVR Addon API discussions in the forum and the xbmc PRs that are flagged with "PVR" and "API change", then you can raise your voice in time. You can be assured that we ofc not break things by intention.

**Comment by ksooo** [comment]
BTW: Any plans, to implement the series recording changes introduced by 2.0.0?

**Comment by ksooo** [comment]
> The -1 values are for a reason since 0 is a valid id from the backend.
> @margro Any chance that you come up with a PR fixing this?

**Pull request merged**
