### PR TITLE
Use system's Live555 libraries when they are available

### PR DESCRIPTION
**Pull request by rbalint**
This adds a dependency on pkg-config but it can be made conditional, too.
Tested on Debian unstable, this is part of the official Debian package now.

### CODE REVIEW

**Comment by margro** [comment]
I'm not going to merge this now. The system live555 library does not work. The latest upstream live555 does not work either.

We need this particular _subset_ of an old live555 version to get RTSP streaming from Mediaportal working. MediaPortal itself is also using this particular version.
So before merging this one, we first need to figure out why only the embedded version works fine.

Note that if it a problem for Debian to use the embedded live555, it is always possible to disable live555 support for now... The addon can work without it.

**Comment by rbalint** [comment]
Thank you for the detailed answer. Is this true for all Mediaportal versions?
I guess then this thread is not about upgrading to the latest live555 version:
http://forum.team-mediaportal.com/threads/rtsp-streaming-library-update.132521/page-6
I'm open to reverting to using the embedded version in Debian if the system version does not work.

**Comment by margro** [comment]
@rbalint Thanks for pointing me to that thread. It is indeed about updating the live555 server and client code in MediaPortal. I missed that thread and haven't seen the code changes since it is not yet in the main repository. I will check their modifications and try if this the missing piece of the puzzle to update to the latest live555 library.

**Comment by ksooo** [comment]
Please reopen for Matrix if you feel this is still of interest.

**Pull request closed without merging**
